[package]
name = "printhor-hwi_native"
version = "0.0.4"
edition = "2021"
authors = ["Carlos Barrales Ruiz <cbruiz@gmail.com>"]
description = "Printhor Hardware Abstraction native std for debugging/playgrounding/analysis"
readme = "README.md"
repository = "https://github.com/cbruiz/printhor"
keywords = ["hardware", "abstration", "library", "printhor"]
license = "MIT"
documentation = "https://docs.rs/printhor-hwi_native"
homepage = "https://github.com/cbruiz/printhor"

[lib]

[features]
# Hardware device features
with-log = ["printhor-hwa-common/with-log"]
with-serial-port-1 = ["async-std"]
with-serial-port-2 = []
with-serial-port-usb = []
with-printjob = []
with-hot-end = ["embedded-hal", "printhor-hwa-common/with-hot-end"]
with-hot-bed = ["embedded-hal", "printhor-hwa-common/with-hot-bed"]
with-motion = ["printhor-hwa-common/with-motion"]
with-probe = ["embedded-hal"]
with-endstops = []
with-sdcard = ["embedded-sdmmc"]
with-fan-layer = ["embedded-hal"]
with-fan-extra-1 = ["embedded-hal"]
with-laser = ["embedded-hal"]
with-trinamic = ["tmc2209"]
with-ps-on = []
with-spi = ["embedded-hal"]

with-display = []


with-x-axis = []
with-y-axis = []
with-z-axis = []
with-e-axis = []

nightly = ["embassy-executor/nightly"]
executor-interrupt = []
verbose-timings = []
sdcard-uses-spi = []
without-vref-int = []

#with-display = [
#    "embedded-graphics-simulator", "embedded-graphics-core", "embedded-graphics",
#    "printhor-hwa-common/with-ui",
#]

[dependencies]

embassy-executor = { version = "0.6.0", default-features = false, features = ["arch-std", "executor-thread", "task-arena-size-16384"] }
embassy-sync = { version = "*", features = ["std"] }
embassy-time = { version = "*", features = ["std", "generic-queue-128"] }
embassy-futures = { version = "*", features = [] }
embassy-embedded-hal = { version = "*", features = [] }

embedded-io-async = { version = "0.6.0", optional = true }
embedded-io = { version = "0.6.1", optional = true }

async-std = { version = "1.12.0", optional = true}
gnuplot = {version = "0.0.38", default-features = false, features=[], optional = true}
#embedded-graphics-simulator = { version = "0.4.1", optional = true }
log = { version = "0.4.20" }
env_logger = { version = "0.10.1" }
printhor-hwa-common = { version = "0.0"}
async-gcode = {version = "0", default-features = false, features=["parse-trailing-comment", "optional-value", "string-value", "std"] }
embedded-hal = { version = "1.0.0", default-features = false, optional = true }
embedded-hal-02 = { package = "embedded-hal", version = "0.2.7", features = ["unproven" ] }
futures = { version = "0.3.30", default-features = false, features = [] }
embedded-sdmmc = { version = "0.8.0", default-features = false, optional = true }

lvgl = { version="0", default-features = false, features =[], optional = true }
#embedded-graphics = { version = "0.8.1", optional = true}
#embedded-graphics-core = {version = "0.4.0", optional = true }
nb = {version = "1.1.0", default-features = false, features = []}
tmc2209 = { version = "0.2.2", optional = true }
thread-priority = { version = "0.15"}

cfg-if = {version = "1.0.0"}
const_env = { version = "0.1" }

[patch.crates-io]
#embassy-stm32 = { git = "https://github.com/cbruiz/embassy.git", branch="main"}
#embassy-executor = { git = "https://github.com/cbruiz/embassy.git", branch="main"}
#embassy-sync = { git = "https://github.com/cbruiz/embassy.git", branch="main" }
#embassy-time = { git = "https://github.com/cbruiz/embassy.git", branch="main" }
#embassy-futures = { git = "https://github.com/cbruiz/embassy.git", branch="main" }
#embassy-embedded-hal = { git = "https://github.com/cbruiz/embassy.git", branch="main" }
async-gcode = { path = "../../libs/async-gcode" }
