[package]
name = "printhor-hwi_native"
version = "0.0.2"
edition = "2021"
authors = ["Carlos Barrales Ruiz <cbruiz@gmail.com>"]
description = "Printhor Hardware Abstraction native std for debugging/playgrounding/analysis"
readme = "README.md"
repository = "https://github.com/cbruiz/printhor"
keywords = ["hardware", "abstration", "library", "printhor"]
license = "MIT"
documentation = "https://docs.rs/printhor-hwi_native"
homepage = "https://github.com/cbruiz/printhor"

[lib]

[features]
# Hardware device features
nightly = []
with-log = ["printhor-hwa-common/with-log"]
with-uart-port-1 = ["async-std"]
with-printjob = []
with-hotend = ["embedded-hal"]
with-hotbed = ["embedded-hal"]
with-motion = []
with-probe = ["embedded-hal"]
with-endstops = []
with-sdcard = ["embedded-sdmmc"]
with-fan-layer = ["embedded-hal"]
with-laser = ["embedded-hal"]
with-trinamic = ["tmc2209"]
sdcard-uses-spi = []

with-display = [
    "embedded-graphics-simulator", "embedded-graphics-core", "embedded-graphics",
    "printhor-hwa-common/with-ui",
]

[dependencies]

embassy-executor = { version = "0", default-features = false, features = ["arch-std", "executor-thread", "task-arena-size-24576"] }
embassy-sync = { version = "0", features = ["std"] }
embassy-time = { version = "0", features = ["std", "generic-queue-32"] }
embassy-futures = { version = "0", features = [] }
embassy-embedded-hal = { version = "0", features = [] }
embassy-usb = { version = "0", features = [], optional = true }

embedded-io-async = { version = "0.6.0", optional = true }
embedded-io = { version = "0.6.1", optional = true }

async-std = { version = "1.12.0", optional = true}
gnuplot = {version = "0.0.38", default-features = false, features=[], optional = true}
embedded-graphics-simulator = { version = "0.4.1", optional = true }
log = { version = "0.4.20" }
env_logger = { version = "0.10.1" }
printhor-hwa-common = { version = "0"}
async-gcode = {version = "0", default-features = false, features=["parse-trailing-comment", "optional-value", "string-value", "std"] }
embedded-hal = { version = "1", default-features = false, optional = true }
embedded-hal-02 = { package = "embedded-hal", version = "0", features = ["unproven", ] }
futures = { version = "0.3.30", default-features = false, features = [] }
embedded-sdmmc = { version = "0.5.0", default-features = false, optional = true }

lvgl = { version="0", default-features = false, features =[], optional = true }
embedded-graphics = { version = "0.7.1", optional = true}
embedded-graphics-core = {version = "0.3.3", optional = true }
nb = {version = "1.1.0", default-features = false, features = []}
tmc2209 = { version = "0.2.2", optional = true }

[patch.crates-io]
embassy-stm32 = { git = "https://github.com/cbruiz/embassy.git", branch="main"}
embassy-executor = { git = "https://github.com/cbruiz/embassy.git", branch="main"}
embassy-sync = { git = "https://github.com/cbruiz/embassy.git", branch="main" }
embassy-time = { git = "https://github.com/cbruiz/embassy.git", branch="main" }
embassy-futures = { git = "https://github.com/cbruiz/embassy.git", branch="main" }
embassy-embedded-hal = { git = "https://github.com/cbruiz/embassy.git", branch="main" }
