[package]
name = "printhor-hwi_native"
version = "0.0.1"
edition = "2021"
authors = ["Carlos Barrales Ruiz <cbruiz@gmail.com>"]
description = "Printhor Hardware Abstraction native std for debugging/playgrounding/analysis"
readme = "README.md"
repository = "https://github.com/cbruiz/printhor"
keywords = ["hardware", "abstration", "library", "printhor"]
license = "MIT"
documentation = "https://docs.rs/printhor-hwi_native"
homepage = "https://github.com/cbruiz/printhor"

[lib]

[features]
# Hardware device features
with-uart-port-1 = ["async-std"]
with-printjob = []
with-hotend = ["embedded-hal"]
with-hotbed = ["embedded-hal"]
with-motion = []
with-probe = ["embedded-hal"]
with-endstops = []
with-sdcard = ["embedded-sdmmc"]
with-fan0 = ["embedded-hal"]
with-fan1 = ["embedded-hal"]
with-laser = ["embedded-hal"]
with-trinamic = []
sdcard-uses-spi = []

with-display = [
    "embedded-graphics-simulator", "embedded-graphics-core", "embedded-graphics",
    "printhor-hwa-common/with-ui",
]

#"log", "env_logger",


[dependencies]

embassy-executor = { version = "*", default-features = false, git = "https://github.com/embassy-rs/embassy", rev = "e0727fe1f6bd1b8c9c356f33991b522956251ba1", features = ["arch-std", "executor-thread", "nightly", "integrated-timers"] }
#embassy-executor = { version = "*", default-features = false, path = "../../../embassy/embassy-executor", features = ["arch-std", "executor-thread", "nightly", "integrated-timers"] }
embassy-sync = { version = "*", git = "https://github.com/embassy-rs/embassy", rev = "e0727fe1f6bd1b8c9c356f33991b522956251ba1", features = ["std"] }
#embassy-sync = { version = "*", path = "../../../embassy/embassy-sync", features = ["std"] }
embassy-time = { version = "*", git = "https://github.com/embassy-rs/embassy", rev = "e0727fe1f6bd1b8c9c356f33991b522956251ba1", features = ["std", "generic-queue"] }
#embassy-time = { version = "*", path = "../../../embassy/embassy-time", features = ["std", "generic-queue"] }
embassy-futures = { version = "*", git = "https://github.com/embassy-rs/embassy", rev = "e0727fe1f6bd1b8c9c356f33991b522956251ba1", features = [] }
#embassy-futures = { version = "*", path = "../../../embassy/embassy-futures", features = [] }
embassy-embedded-hal = { version = "*", git = "https://github.com/embassy-rs/embassy", rev = "e0727fe1f6bd1b8c9c356f33991b522956251ba1", features = ["nightly"] }
#embassy-embedded-hal = { version = "*", path = "../../../embassy/embassy-embedded-hal", features = ["nightly"] }
embassy-usb = { version = "*", git = "https://github.com/embassy-rs/embassy", rev = "e0727fe1f6bd1b8c9c356f33991b522956251ba1", features = [], optional = true }
#embassy-usb = { version = "*", path = "../../../embassy/embassy-usb", features = [], optional = true }

#nix = { version = "0.27.1", optional = true }
embedded-io-async = { version = "0.6.0", optional = true }
embedded-io = { version = "0.6.1", optional = true }

async-std = { version = "*", optional = true}
gnuplot = {version = "0.0.38", default-features = false, features=[], optional = true}
embedded-graphics-simulator = { version = "0.4.1", optional = true }
log = { version = "0.4.20" }
env_logger = { version = "0.10.1" }


printhor-hwa-common = { version = "*", path= "../../printhor-hwa-common" }
async-gcode = {version = "*", default-features = false, features=["parse-trailing-comment", "optional-value", "string-value"], git="https://github.com/cbruiz/async-gcode.git", branch= "feature/embedded-productivization" }
embedded-hal = { version = "0.2.3", default-features = false, optional = true }
futures = { version = "0.3.29", default-features = false, features = [] }
embedded-sdmmc = { version = "0.5.0", default-features = false, optional = true }

lvgl = { version="*", git = "https://github.com/nviennot/lvgl-rs.git", default-features = false, features =[], optional = true }
embedded-graphics = { version = "0.7.1", optional = true}
embedded-graphics-core = {version = "0.3.3", optional = true }