[package]
name = "printhor-hwa-common"
version = "0.0.1"
edition = "2021"
authors = ["Carlos Barrales Ruiz <cbruiz@gmail.com>"]
description = "Printor harware abstraction utillery"
readme = "README.md"
repository = "https://github.com/cbruiz/printhor"
keywords = ["hardware", "abstration", "library", "printhor"]
categories = ["hardware-support"]
license = "MIT"
documentation = "https://docs.rs/printhor-hwa_common"
homepage = "https://github.com/cbruiz/printhor"

[lib]

[features]
with-ui=["embedded-graphics-core"]

[dependencies]
portable-atomic = { version = "1.5.1",  default-features = false, features = ["critical-section"] }
static_cell = { version = "2.0.0",  default-features = false, features = ["nightly"] }
embassy-sync = { version = "*", git = "https://github.com/embassy-rs/embassy", rev = "e0727fe1f6bd1b8c9c356f33991b522956251ba1", features = ["nightly"] }
#embassy-sync = { version = "*", path="../../../embassy/embassy-sync", features = ["nightly"] }

embedded-graphics-core = {version = "0.3.3", optional = true }
bitflags = { version = "2.4.1", default-features = false, features = ["bytemuck"] }
