[package]
name = "printhor-hwa-common"
version = "0.0.3"
edition = "2021"
authors = ["Carlos Barrales Ruiz <cbruiz@gmail.com>"]
description = "Printor harware abstraction utillery"
readme = "README.md"
repository = "https://github.com/cbruiz/printhor"
keywords = ["hardware", "abstration", "library", "printhor"]
categories = ["hardware-support"]
license = "MIT"
documentation = "https://docs.rs/printhor-hwa_common"
homepage = "https://github.com/cbruiz/printhor"

[lib]

[features]
with-ui = ["embedded-graphics-core"]
nightly = []
with-log = ["log"]
with-defmt = ["defmt"]
with-motion = []
with-hotend = []
with-hotbed = []

[dependencies]
portable-atomic = { version = "1.6.0",  default-features = false, features = ["critical-section"] }
static_cell = { version = "2.0.0",  default-features = false, features = [] }

embassy-sync = { version = "0.5.0", features = [] }
embassy-time = { version = "0.3.0", features = [] }

embedded-hal = { version = "1.0.0", default-features = false }
embedded-hal-02 = { package = "embedded-hal", version = "0.2.7", features = ["unproven"] }

embedded-graphics-core = {version = "0.3.3", optional = true }
bitflags = { version = "2.4.1", default-features = false, features = ["bytemuck"] }
defmt = {version = "0.3", default-features = false, optional = true}
log = { version = "0.4.20", default-features = false, optional = true }
