[target.'cfg(all(any(board="nucleo64-f410rb"), target_arch="arm", target_os="none"))']
runner = "probe-rs run --chip STM32F410RBTx --disable-progressbars"

[target.'cfg(all(any(board="nucleo64-l476rg"), target_arch="arm", target_os="none"))']
runner = "probe-rs run --chip STM32L476RG --disable-progressbars"

[target.'cfg(all(any(board="skr_mini_e3"), target_arch="arm", target_os="none"))']
runner = "probe-rs run --chip STM32G0B1RETx --disable-progressbars"

[target.'cfg(all(any(board="mks_robin_nano"), target_arch="arm", target_os="none"))']
runner = "probe-rs run --chip STM32F407VETx --disable-progressbars"

[build]

[env]
DEFMT_LOG = "info"
RUST_LOG = "info"
ASYNC_STD_THREAD_COUNT = "1"

[profile.dev.package."*"]
codegen-units = 1
incremental = false
#opt-level = "s"
debug = 2
debug-assertions = true
overflow-checks = true

[profile.release.package."*"]
codegen-units = 1
incremental = false
opt-level = "s"
debug = 2
debug-assertions = false
overflow-checks = false
